# Generated by Django 3.2 on 2021-12-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeopleDataForPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('jobTitle', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInsightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='spns_cover_image/')),
                ('heading', models.CharField(max_length=350)),
                ('intro_content', models.TextField(default='..')),
                ('pdf_file', models.FileField(blank=True, upload_to='researcch_and_insight')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('main_content', models.TextField()),
                ('intro_content', models.TextField(max_length=300)),
                ('icon_class', models.CharField(default='..', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='researchinsight_ParaGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('researchinsightinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.researchinsightinfo')),
            ],
        ),
    ]
